# basic options
title: Ugi's page
Author: Ugi
email: javest@utu.fi
description: My page to display some of the projects I've done
github_username: Ugi0

#build settings
markdown: kramdown
theme: minima
